import { leaveTypes } from '@/enums/leaveTypes';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { AllocatedLeaveDto } from '@/types/my-leave/my-leave.type';

export const formSchema: FormField[] = [
  {
    column: 4,
    align: 'default',
    label: 'Fiscal Year',
    labelVisibility: 'visible',
    fieldName: 'fiscalYear',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Total Sick Leave',
    labelVisibility: 'visible',
    fieldName: 'totalSickLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Taken Sick Leave',
    labelVisibility: 'visible',
    fieldName: 'takenSickLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Total Casual Leave',
    labelVisibility: 'visible',
    fieldName: 'totalCasualLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Taken Casual Leave',
    labelVisibility: 'visible',
    fieldName: 'takenCasualLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Total Annual Leave',
    labelVisibility: 'visible',
    fieldName: 'totalAnnualLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Taken Annual Leave',
    labelVisibility: 'visible',
    fieldName: 'takenAnnualLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Paid Leave',
    labelVisibility: 'visible',
    fieldName: 'paidLeave',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const TableSchema: TableHead<AllocatedLeaveDto>[] = [
  {
    label: 'User Name',
    accessor: 'userName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Fiscal Year',
    accessor: 'fiscalYear',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Sick Leave',
    accessor: 'sickLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Casual Leave',
    accessor: 'casualLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Annual Leave',
    accessor: 'annualLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Paid Leave',
    accessor: 'paidLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
