import { leaveFor } from '@/enums/leaveFor';
import { leaveTypes } from '@/enums/leaveTypes';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import {
  AllocatedLeaveDto,
  LeaveRequestDto,
} from '@/types/my-leave/my-leave.type';

export const formSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Subject',
    labelVisibility: 'visible',
    fieldName: 'reason',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave Type',
    labelVisibility: 'visible',
    fieldName: 'leaveType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave For',
    labelVisibility: 'visible',
    fieldName: 'leaveFor',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveFor,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'From Date',
    labelVisibility: 'visible',
    fieldName: 'fromDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'To Date',
    labelVisibility: 'visible',
    fieldName: 'toDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Attchment',
    labelVisibility: 'visible',
    fieldName: 'attchmentPath',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const allocateTableSchema: TableHead<AllocatedLeaveDto>[] = [
  {
    label: 'Fiscal Year',
    accessor: 'fiscalYear',
    sortable: true,
    searchable: false,
    align: 'start',
  },
  {
    label: 'Sick Leave',
    accessor: 'sickLeave',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'Casual Leave',
    accessor: 'casualLeave',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'Annual Leave',
    accessor: 'annualLeave',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'Paid Leave',
    accessor: 'paidLeave',
    sortable: true,
    searchable: false,
    align: 'center',
  },
];

export const tableSchema: TableHead<LeaveRequestDto>[] = [
  {
    label: 'Leave Type',
    accessor: 'leaveType',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Leave For',
    accessor: 'leaveFor',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'From Date',
    accessor: 'fromDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'To Date',
    accessor: 'toDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Days',
    accessor: 'totalDay',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'Status',
    accessor: 'leaveStatus',
    sortable: true,
    searchable: false,
    align: 'center',
  },
];
