import { leaveFor } from '@/enums/leaveFor';
import { leaveTypes } from '@/enums/leaveTypes';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { AllocatedLeaveDto, LeaveDto } from '@/types/my-leave/my-leave.type';
import { TaskDto } from '@/types/task-board/task.type';

export const formSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Subject',
    labelVisibility: 'visible',
    fieldName: 'subject',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave Type',
    labelVisibility: 'visible',
    fieldName: 'leaveType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave For',
    labelVisibility: 'visible',
    fieldName: 'leavefor',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveFor,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'From Date',
    labelVisibility: 'visible',
    fieldName: 'FromDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'To Date',
    labelVisibility: 'visible',
    fieldName: 'toDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Attchment',
    labelVisibility: 'visible',
    fieldName: 'attchment',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const allocateTableSchema: TableHead<AllocatedLeaveDto>[] = [
  {
    label: 'Fiscal Year',
    accessor: 'fiscalYear',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Sick Leave',
    accessor: 'totalSickLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Annual Leave',
    accessor: 'totalAnnualLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },

  {
    label: 'Casual Leave',
    accessor: 'totalCasualLeave',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];

export const tableSchema: TableHead<LeaveDto>[] = [
  {
    label: 'Leave Type',
    accessor: 'leaveType',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Leave For',
    accessor: 'leaveFor',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'From Date',
    accessor: 'fromDate',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'To Date',
    accessor: 'toDate',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Days',
    accessor: 'days',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
