import { bloodGroups } from '@/enums/bloodGroups';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { UserDto } from '@/types/master-data/user.type';

export const userFormSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Full Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Department',
    labelVisibility: 'visible',
    fieldName: 'departmentId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
    onChange: 'handleDepartmentChange',
  },
  {
    column: 6,
    align: 'default',
    label: 'Designation',
    labelVisibility: 'visible',
    fieldName: 'designationId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Role',
    labelVisibility: 'visible',
    fieldName: 'roleId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Date of Birth',
    labelVisibility: 'visible',
    fieldName: 'dob',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Phone',
    labelVisibility: 'visible',
    fieldName: 'phone',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Email',
    labelVisibility: 'visible',
    fieldName: 'email',
    dataType: 'email',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Current Address',
    labelVisibility: 'visible',
    fieldName: 'currentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Present Address',
    labelVisibility: 'visible',
    fieldName: 'presentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Blood Group',
    labelVisibility: 'visible',
    fieldName: 'bloodGroup',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Profile',
    labelVisibility: 'visible',
    fieldName: 'profileIcon',
    dataType: 'image',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Password',
    labelVisibility: 'visible',
    fieldName: 'password',
    dataType: 'password',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
];

export const userFormUpdatedSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Full Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Department',
    labelVisibility: 'visible',
    fieldName: 'departmentId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
    onChange: 'handleDepartmentChange',
  },
  {
    column: 6,
    align: 'default',
    label: 'Designation',
    labelVisibility: 'visible',
    fieldName: 'designationId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Role',
    labelVisibility: 'visible',
    fieldName: 'roleId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Date of Birth',
    labelVisibility: 'visible',
    fieldName: 'dob',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Phone',
    labelVisibility: 'visible',
    fieldName: 'phone',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Email',
    labelVisibility: 'visible',
    fieldName: 'email',
    dataType: 'email',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Current Address',
    labelVisibility: 'visible',
    fieldName: 'currentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Present Address',
    labelVisibility: 'visible',
    fieldName: 'presentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Blood Group',
    labelVisibility: 'visible',
    fieldName: 'bloodGroup',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Password',
    labelVisibility: 'visible',
    fieldName: 'password',
    dataType: 'password',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: false,
  },
];

export const userFormViewSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Full Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Department',
    labelVisibility: 'visible',
    fieldName: 'departmentId',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: true,
    onChange: 'handleDepartmentChange',
  },
  {
    column: 6,
    align: 'default',
    label: 'Designation',
    labelVisibility: 'visible',
    fieldName: 'designationId',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Role',
    labelVisibility: 'visible',
    fieldName: 'roleId',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Date of Birth',
    labelVisibility: 'visible',
    fieldName: 'dob',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Phone',
    labelVisibility: 'visible',
    fieldName: 'phone',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Email',
    labelVisibility: 'visible',
    fieldName: 'email',
    dataType: 'email',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Current Address',
    labelVisibility: 'visible',
    fieldName: 'currentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Present Address',
    labelVisibility: 'visible',
    fieldName: 'presentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Blood Group',
    labelVisibility: 'visible',
    fieldName: 'bloodGroup',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Profile',
    labelVisibility: 'visible',
    fieldName: 'profileIcon',
    dataType: 'image',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    disabled: true,
  },
];

export const userTableSchema: TableHead<UserDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Department',
    accessor: 'departmentName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Designation',
    accessor: 'designationName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Role',
    accessor: 'roleName',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Status',
    accessor: 'active',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
