import { bloodGroups } from '@/enums/bloodGroups';
import { FormField } from '@/types/common/FormField';

export const userFormSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Full Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Department',
    labelVisibility: 'visible',
    fieldName: 'departmentId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    onChange: 'handleDepartmentChange',
  },
  {
    column: 6,
    align: 'default',
    label: 'Designation',
    labelVisibility: 'visible',
    fieldName: 'designationId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Role',
    labelVisibility: 'visible',
    fieldName: 'roleId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Date of Birth',
    labelVisibility: 'visible',
    fieldName: 'dob',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Phone',
    labelVisibility: 'visible',
    fieldName: 'phone',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Email',
    labelVisibility: 'visible',
    fieldName: 'email',
    dataType: 'email',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Current Address',
    labelVisibility: 'visible',
    fieldName: 'currentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Present Address',
    labelVisibility: 'visible',
    fieldName: 'presentAddress',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Blood Group',
    labelVisibility: 'visible',
    fieldName: 'bloodGroup',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Profile',
    labelVisibility: 'visible',
    fieldName: 'profile',
    dataType: 'image',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Password',
    labelVisibility: 'visible',
    fieldName: 'password',
    dataType: 'password',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: bloodGroups,
    isRequired: true,
  },
];
