import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { ProjectDto } from '@/types/master-data/project.type';

export const projectFormSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Start Date',
    labelVisibility: 'visible',
    fieldName: 'startDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'End Date',
    labelVisibility: 'visible',
    fieldName: 'endDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Assine To Users',
    labelVisibility: 'visible',
    fieldName: 'assignToUser',
    dataType: 'multi-select',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const projectTableSchema: TableHead<ProjectDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Start Date',
    accessor: 'startDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'endDate',
    accessor: 'endDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
];
