import { leaveFor } from '@/enums/leaveFor';
import { leaveTypes } from '@/enums/leaveTypes';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { LeaveRequestDto } from '@/types/my-leave/my-leave.type';

export const formCompleteSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Reason',
    labelVisibility: 'visible',
    fieldName: 'reason',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave Type',
    labelVisibility: 'visible',
    fieldName: 'leaveType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave For',
    labelVisibility: 'visible',
    fieldName: 'leaveFor',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveFor,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'From Date',
    labelVisibility: 'visible',
    fieldName: 'fromDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'To Date',
    labelVisibility: 'visible',
    fieldName: 'toDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Total Day',
    labelVisibility: 'visible',
    fieldName: 'totalDay',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Attchment',
    labelVisibility: 'visible',
    fieldName: 'attchment',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 12,
    align: 'default',
    label: 'Remarks',
    labelVisibility: 'visible',
    fieldName: 'remarks',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const formViewSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Reason',
    labelVisibility: 'visible',
    fieldName: 'reason',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave Type',
    labelVisibility: 'visible',
    fieldName: 'leaveType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveTypes,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Leave For',
    labelVisibility: 'visible',
    fieldName: 'leaveFor',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: leaveFor,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'From Date',
    labelVisibility: 'visible',
    fieldName: 'fromDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'To Date',
    labelVisibility: 'visible',
    fieldName: 'toDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Total Day',
    labelVisibility: 'visible',
    fieldName: 'totalDay',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Attchment',
    labelVisibility: 'visible',
    fieldName: 'attchment',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
];

export const tableSchema: TableHead<LeaveRequestDto>[] = [
  {
    label: 'Name',
    accessor: 'userName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Leave Type',
    accessor: 'leaveType',
    sortable: true,
    searchable: false,
    align: 'start',
  },
  {
    label: 'Leave For',
    accessor: 'leaveFor',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'From Date',
    accessor: 'fromDate',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'To Date',
    accessor: 'toDate',
    sortable: true,
    searchable: false,
    align: 'center',
  },
  {
    label: 'Total Day',
    accessor: 'totalDay',
    sortable: true,
    searchable: false,
    align: 'end',
  },
];
