import { MenuTables } from '@/types/master-data/menu.type';

export const menus: MenuTables[] = [
  {
    id: 1,
    name: 'Dashboard',
    menuType: 'MAIN',
    parentId: null,
    parentMenu: '',
    icon: 'bi bi-speedometer2',
    path: '/dashboard',
  },
  {
    id: 2,
    name: 'Users',
    menuType: 'MAIN',
    parentId: null,
    parentMenu: '',
    icon: 'bi bi-people',
    path: '/users',
  },
  {
    id: 3,
    name: 'User List',
    menuType: 'SUB',
    parentId: '2',
    parentMenu: 'Users',
    icon: 'bi bi-list-ul',
    path: '/users/list',
  },
  {
    id: 4,
    name: 'User Roles',
    menuType: 'SUB',
    parentId: '2',
    parentMenu: 'Users',
    icon: 'bi bi-shield-lock',
    path: '/users/roles',
  },
  {
    id: 5,
    name: 'Settings',
    menuType: 'MAIN',
    parentId: null,
    parentMenu: '',
    icon: 'bi bi-gear',
    path: '/settings',
  },
  {
    id: 6,
    name: 'Profile',
    menuType: 'SUB',
    parentId: '5',
    parentMenu: 'Settings',
    icon: 'bi bi-person',
    path: '/settings/profile',
  },
  {
    id: 7,
    name: 'Security',
    menuType: 'SUB',
    parentId: '5',
    parentMenu: 'Settings',
    icon: 'bi bi-lock',
    path: '/settings/security',
  },
  {
    id: 8,
    name: 'Reports',
    menuType: 'MAIN',
    parentId: null,
    parentMenu: '',
    icon: 'bi bi-bar-chart',
    path: '/reports',
  },
  {
    id: 9,
    name: 'Sales Report',
    menuType: 'SUB',
    parentId: '8',
    parentMenu: 'Reports',
    icon: 'bi bi-graph-up',
    path: '/reports/sales',
  },
  {
    id: 10,
    name: 'Inventory Report',
    menuType: 'SUB',
    parentId: '8',
    parentMenu: 'Reports',
    icon: 'bi bi-box-seam',
    path: '/reports/inventory',
  },
];
