import { FormField } from '@/types/common/FormField';

export const menuFormSchema: FormField[] = [
  {
    column: 4,
    align: 'default',
    label: 'Menu Type',
    labelVisibility: 'visible',
    fieldName: 'menuType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [
      { id: 'MAIN', name: 'Main Menu' },
      { id: 'SUB', name: 'Sub Menu' },
    ],
    isRequired: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Menu Name',
    labelVisibility: 'visible',
    fieldName: 'menuName',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: [{ field: 'menuType', value: 'MAIN' }],
  },
  {
    column: 4,
    align: 'default',
    label: 'Menu List',
    labelVisibility: 'visible',
    fieldName: 'parentId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: [{ field: 'menuType', value: 'SUB' }],
  },
  {
    column: 4,
    align: 'default',
    label: 'Sub-Menu Name',
    labelVisibility: 'visible',
    fieldName: 'subName',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: [{ field: 'menuType', value: 'SUB' }],
  },
  {
    column: 4,
    align: 'default',
    label: 'Icon',
    labelVisibility: 'visible',
    fieldName: 'icon',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: [{ field: 'menuType', value: 'MAIN' }],
  },
  {
    column: 4,
    align: 'default',
    label: 'path',
    labelVisibility: 'visible',
    fieldName: 'path',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: [{ field: 'menuType', value: 'SUB' }],
  },
  {
    column: 4,
    align: 'default',
    label: 'path',
    labelVisibility: 'visible',
    fieldName: 'path',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: [{ field: 'menuType', value: 'MAIN' }],
  },
];
