import { taskPriority } from '@/enums/priority';
import { taskTracker } from '@/enums/taskTracker';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { TaskDto } from '@/types/task-board/task.type';

export const formSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Project',
    labelVisibility: 'visible',
    fieldName: 'projectId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: 'handleProjectChange',
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Target Sprint',
    labelVisibility: 'visible',
    fieldName: 'sprintId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Assignee',
    labelVisibility: 'visible',
    fieldName: 'userId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Task Tracker',
    labelVisibility: 'visible',
    fieldName: 'taskTracker',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: taskTracker,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Priority',
    labelVisibility: 'visible',
    fieldName: 'priority',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: taskPriority,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Estimated Time(Hrs)',
    labelVisibility: 'visible',
    fieldName: 'estimatedTime',
    dataType: 'hour',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Files',
    labelVisibility: 'visible',
    fieldName: 'file',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const moveFormSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 12,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Current Sprint',
    labelVisibility: 'visible',
    fieldName: 'currentSprintName',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 6,
    align: 'default',
    label: 'Target Sprint',
    labelVisibility: 'visible',
    fieldName: 'sprintId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Remarks',
    labelVisibility: 'visible',
    fieldName: 'remarks',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const tableSchema: TableHead<TaskDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Project Name',
    accessor: 'projectName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Sprint Name',
    accessor: 'sprintName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Priority',
    accessor: 'priority',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Assign User',
    accessor: 'userName',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
