import { sprintTypes } from '@/enums/sprintTypes';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { SprintDto } from '@/types/master-data/sprint.type';

export const formSchema: FormField[] = [
  {
    column: 6,
    align: 'default',
    label: 'Project',
    labelVisibility: 'visible',
    fieldName: 'projectId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Start Date',
    labelVisibility: 'visible',
    fieldName: 'startDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'End Date',
    labelVisibility: 'visible',
    fieldName: 'endDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Working Days',
    labelVisibility: 'visible',
    fieldName: 'workingDays',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'Daily Working(Hrs)',
    labelVisibility: 'visible',
    fieldName: 'dailyWorkingHrs',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 6,
    align: 'default',
    label: 'SprintType',
    labelVisibility: 'visible',
    fieldName: 'sprintType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: sprintTypes,
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const tableSchema: TableHead<SprintDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Project Name',
    accessor: 'projectName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Start Date',
    accessor: 'startDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'End Date',
    accessor: 'endDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Sprint Hours',
    accessor: 'totalSprintHrs',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Status',
    accessor: 'sprintType',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
