import { FormField } from "@/types/common/FormField";

export const missionSchema : FormField[] = [
  {
    column: 4,
    align: "default",
    label: "Name",
    labelVisibility:"visible",
    fieldName: "name",
    dataType: "text",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
    {
    column: 4,
    align: "default",
    label: "Mission Description",
    labelVisibility:"visible",
    fieldName: "missionDescription",
    dataType: "text",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  
  {
    column: 4,
    align: "default",
    label: "Raising Date",
    labelVisibility:"visible",
    fieldName: "raisingDate",
    dataType: "date",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Mission Country",
    labelVisibility:"visible",
    fieldName: "missionCountryId",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Start Date",
    labelVisibility:"visible",
    fieldName: "startDate",
    dataType: "date",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "End Date",
    labelVisibility:"visible",
    fieldName: "endDate",
    dataType: "date",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  
];
