import { taskPriority } from '@/enums/priority';
import { taskTracker } from '@/enums/taskTracker';
import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { SprintDto } from '@/types/master-data/sprint.type';

export const formSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Project',
    labelVisibility: 'visible',
    fieldName: 'projectId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: 'handleProjectChange',
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Target Sprint',
    labelVisibility: 'visible',
    fieldName: 'sprintId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Assignee',
    labelVisibility: 'visible',
    fieldName: 'userId',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Task Tracker',
    labelVisibility: 'visible',
    fieldName: 'taskTracker',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: taskTracker,
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Priority',
    labelVisibility: 'visible',
    fieldName: 'priority',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: taskPriority,
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Task Type',
    labelVisibility: 'visible',
    fieldName: 'taskType',
    dataType: 'dropdown',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [{ id: 'UNPLANNED', name: 'Unplanned' }],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Start Date',
    labelVisibility: 'visible',
    fieldName: 'startDate',
    dataType: 'date',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Estimated Time(Hrs)',
    labelVisibility: 'visible',
    fieldName: 'estimatedTime',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 4,
    align: 'default',
    label: 'Files',
    labelVisibility: 'visible',
    fieldName: 'files',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const tableSchema: TableHead<SprintDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Project Name',
    accessor: 'projectName',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Start Date',
    accessor: 'startDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'End Date',
    accessor: 'endDate',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Sprint Hours',
    accessor: 'totalSprintHrs',
    sortable: true,
    searchable: true,
    align: 'center',
  },
  {
    label: 'Status',
    accessor: 'sprintType',
    sortable: true,
    searchable: true,
    align: 'center',
  },
];
