import { FormField } from "@/types/common/FormField";

export const allowanceSchema : FormField[] = [
  {
    column: 4,
    align: "default",
    label: "Name",
    labelVisibility:"visible",
    fieldName: "name",
    dataType: "text",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Pay Status",
    labelVisibility:"visible",
    fieldName: "payStatus",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Apply For",
    labelVisibility:"visible",
    fieldName: "applyFor",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Calculation Mode",
    labelVisibility:"visible",
    fieldName: "calculationMode",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Action Status",
    labelVisibility:"visible",
    fieldName: "actionStatus",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Duration",
    labelVisibility:"visible",
    fieldName: "duration",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "JSI Duration",
    labelVisibility:"visible",
    fieldName: "jsiDuration",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "processType",
    labelVisibility:"visible",
    fieldName: "processType",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
  
  {
    column: 4,
    align: "default",
    label: "Pay Based On",
    labelVisibility:"visible",
    fieldName: "payBasedOn",
    dataType: "dropdown",
    action: null,
    defaultValue: "",
    isEnum: true,
    enum: [],
    isRequired: true,
  },
    {
    column: 4,
    align: "default",
    label: "Pay AllowanceDetail",
    labelVisibility:"visible",
    fieldName: "payAllowanceDetail",
    dataType: "number",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 4,
    align: "default",
    label: "Budget Code",
    labelVisibility:"visible",
    fieldName: "budgetCode",
    dataType: "text",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 2,
    align: "default",
    label: "No Process Current Month",
    labelVisibility:"hidden",
    fieldName: "noProcessCurrentMonth",
    dataType: "checkbox",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 2,
    align: "default",
    label: "Treat Receivable",
    labelVisibility:"hidden",
    fieldName: "treatReceivable",
    dataType: "checkbox",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  },
  {
    column: 2,
    align: "default",
    label: "Not AllowedPension",
    labelVisibility:"hidden",
    fieldName: "notAllowedPension",
    dataType: "checkbox",
    action: null,
    defaultValue: "",
    isEnum: false,
    enum: [],
    isRequired: true,
  }
];
